require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ConstructionSitesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ConstructionSite. As you add validations to ConstructionSite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConstructionSitesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all construction_sites as @construction_sites" do
      construction_site = ConstructionSite.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:construction_sites)).to eq([construction_site])
    end
  end

  describe "GET show" do
    it "assigns the requested construction_site as @construction_site" do
      construction_site = ConstructionSite.create! valid_attributes
      get :show, {:id => construction_site.to_param}, valid_session
      expect(assigns(:construction_site)).to eq(construction_site)
    end
  end

  describe "GET new" do
    it "assigns a new construction_site as @construction_site" do
      get :new, {}, valid_session
      expect(assigns(:construction_site)).to be_a_new(ConstructionSite)
    end
  end

  describe "GET edit" do
    it "assigns the requested construction_site as @construction_site" do
      construction_site = ConstructionSite.create! valid_attributes
      get :edit, {:id => construction_site.to_param}, valid_session
      expect(assigns(:construction_site)).to eq(construction_site)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ConstructionSite" do
        expect {
          post :create, {:construction_site => valid_attributes}, valid_session
        }.to change(ConstructionSite, :count).by(1)
      end

      it "assigns a newly created construction_site as @construction_site" do
        post :create, {:construction_site => valid_attributes}, valid_session
        expect(assigns(:construction_site)).to be_a(ConstructionSite)
        expect(assigns(:construction_site)).to be_persisted
      end

      it "redirects to the created construction_site" do
        post :create, {:construction_site => valid_attributes}, valid_session
        expect(response).to redirect_to(ConstructionSite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved construction_site as @construction_site" do
        post :create, {:construction_site => invalid_attributes}, valid_session
        expect(assigns(:construction_site)).to be_a_new(ConstructionSite)
      end

      it "re-renders the 'new' template" do
        post :create, {:construction_site => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested construction_site" do
        construction_site = ConstructionSite.create! valid_attributes
        put :update, {:id => construction_site.to_param, :construction_site => new_attributes}, valid_session
        construction_site.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested construction_site as @construction_site" do
        construction_site = ConstructionSite.create! valid_attributes
        put :update, {:id => construction_site.to_param, :construction_site => valid_attributes}, valid_session
        expect(assigns(:construction_site)).to eq(construction_site)
      end

      it "redirects to the construction_site" do
        construction_site = ConstructionSite.create! valid_attributes
        put :update, {:id => construction_site.to_param, :construction_site => valid_attributes}, valid_session
        expect(response).to redirect_to(construction_site)
      end
    end

    describe "with invalid params" do
      it "assigns the construction_site as @construction_site" do
        construction_site = ConstructionSite.create! valid_attributes
        put :update, {:id => construction_site.to_param, :construction_site => invalid_attributes}, valid_session
        expect(assigns(:construction_site)).to eq(construction_site)
      end

      it "re-renders the 'edit' template" do
        construction_site = ConstructionSite.create! valid_attributes
        put :update, {:id => construction_site.to_param, :construction_site => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested construction_site" do
      construction_site = ConstructionSite.create! valid_attributes
      expect {
        delete :destroy, {:id => construction_site.to_param}, valid_session
      }.to change(ConstructionSite, :count).by(-1)
    end

    it "redirects to the construction_sites list" do
      construction_site = ConstructionSite.create! valid_attributes
      delete :destroy, {:id => construction_site.to_param}, valid_session
      expect(response).to redirect_to(construction_sites_url)
    end
  end

end
